config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :users

  namespace :v1 do
    resources :users
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show, :edit, :destroy, :update]
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def show
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    save_user(:new)
  end

  def destroy
    if  @user.destroy
      redirect_to action: :index
    end
  end

  def update
    save_user(:edit)
  end

  private

  def save_user(action)
    if @user.save
      redirect_to action: :index
    else
      render action
    end
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password)
  end

  def find_user
    @user = User.find(params[:id])
  end
end

app/controllers/v1/base_controller.rb
module V1
  class BaseController < ActionController::API
    before_action :find_user, only: [:show, :edit, :destroy, :update]
  end
end

app/controllers/v1/users_controller.rb
module V1
  class UsersController < BaseController
    def index
      @users = User.all
    end

    def show
    end

    def create
      @user = User.new(user_params)
      save_user(:new)
    end

    def destroy
      if  @user.destroy
        render json: {message: 'User deleted successfully'}, status: :ok
      end
    end

    def update
      save_user(:edit)
    end

    private

    def save_user(action)
      if @user.save
        render :show
      else
        render action
      end
    end

    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password)
    end

    def find_user
      @user = User.find(params[:id])
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Social
    = csrf_meta_tags
    = javascript_pack_tag 'application'
  %body
    = yield

app/views/users/_form.html.haml
= form_with model: @user do |f|
  = f.label :first_name
  = f.text_field :first_name

  = f.label :last_name
  = f.text_field :last_name

  = f.label :email
  = f.text_field :email

  = f.label :password
  = f.text_field :password

  = f.submit

app/views/users/edit.html.haml
= render 'form'

app/views/users/index.html.haml
= link_to 'Add User', new_user_path

- @users.each do |user|
  %ol
    %li= user.first_name
    %li= user.last_name
    %li= user.email
  %br

app/views/users/new.html.haml
= render 'form'

app/views/users/show.html.haml
%ol
  %li= @user.first_name
  %li= @user.last_name
  %li= @user.email